### ISSUE TITLE
I want to log out of Google.

### ISSUE THREAD

**Issue by zen551** [yobaji/vue3-google-login#3]
Hello.

I called googleLogout().

But it did not seem to logout.

Could you please provide a sample code of the sequence of steps from login to logout?🙏

**Comment by yobaji** [comment]
`googleLogout` function calls [google.accounts.id.disableAutoSelect](https://developers.google.com/identity/gsi/web/guides/automatic-sign-in-sign-out?hl=en#sign-out) method under the hoods, this is used to disable the auto login feature while using One-Tap prompt.

By 'log out of google' if u mean to clear the google login session from the current browser, I believe it is not possible, google doesn't allow this because user may be using the login session for other applications.

One thing you can do is to revoke a google user in your application using [google.accounts.id.revoke](https://developers.google.com/identity/gsi/web/reference/js-reference#google.accounts.id.revoke) method use the following code snippet

```js
import { googleSdkLoaded } from "vue3-google-login"
const logout = () => {
  googleSdkLoaded((google) => {
    google.accounts.id.revoke("logged_in_user_email@gmail.com")
  })
}
```

**Comment by yobaji** [comment]
`googleLogout` function calls [google.accounts.id.disableAutoSelect](https://developers.google.com/identity/gsi/web/guides/automatic-sign-in-sign-out?hl=en#sign-out) method under the hoods, this is used to disable the auto login feature while using One-Tap prompt.

By 'log out of google' if u mean to clear the google login session from the current browser, I believe it is not possible, google doesn't allow this because user may be using the login session for other applications.

One thing you can do is to revoke a google user in your application using [google.accounts.id.revoke](https://developers.google.com/identity/gsi/web/reference/js-reference#google.accounts.id.revoke) method use the following code snippet

```js
import { googleSdkLoaded } from "vue3-google-login"
const logout = () => {
  googleSdkLoaded((google) => {
    google.accounts.id.revoke("logged_in_user_email@gmail.com")
  })
}
```

**Comment by zen551** [comment]
Sorry for the delay in confirming and thanking you.

My question was flawed, but your answer was perfect.

I learned a lot. Thank you very much.
